<a href="https://colab.research.google.com/github/jeevanraajas0210/ITA0604-Machine-Learning/blob/main/Data_Manipulation_and_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

marks = np.array([70, 85, 60, 90, 75])

print(marks)

[70 85 60 90 75]


In [3]:
import numpy as np

marks = np.array([70, 85, 60, 90, 75])

print("Highest Mark:", np.max(marks))

Highest Mark: 90


In [4]:
import numpy as np

marks = np.array([70, 85, 60, 90, 75])

print("Lowest Mark:", np.min(marks))

Lowest Mark: 60


In [5]:
import numpy as np

marks = np.array([70, 85, 60, 90, 75])

print("Average Mark:", np.mean(marks))

Average Mark: 76.0


In [6]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

print(marks[0])
print(marks[2])

70
90


In [7]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

print(marks[-1])
print(marks[-2])

75
60


In [8]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[0, 0])
print(a[1, 2])

10
60


In [9]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[1])

[40 50 60]


In [10]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(a[:, 1])

[20 50 80]


In [11]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

print(marks[1:4])

[80 90 60]


In [12]:
import numpy as np

fruits = np.array(["Apple", "Mango", "Orange", "Grapes", "Banana"])

print(fruits[0])
print(fruits[2])
print(fruits[-1])

Apple
Orange
Banana
