<a href="https://colab.research.google.com/github/jeevanraajas0210/ITA0604-Machine-Learning/blob/main/ML_ITA0604_21_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])

In [ ]:
output = np.tanh(x)

print("Input Values:")
print(x)

print("Tanh Output:")
print(output)


Input Values:
[-3 -2 -1  0  1  2  3]
Tanh Output:
[-0.99505475 -0.96402758 -0.76159416  0.          0.76159416  0.96402758
  0.99505475]


In [ ]:
print("\nActivation Function: ReLU")

x = np.array([-5, -2, 0, 3, 7])

relu_output = np.maximum(0, x)

print("Input Values:")
print(x)

print("ReLU Output:")
print(relu_output)


Activation Function: ReLU
Input Values:
[-5 -2  0  3  7]
ReLU Output:
[0 0 0 3 7]


In [ ]:
print("\nActivation Function: SIGMOID")

x = np.array([-5, 2, 0, 2, 5])

sigmoid_output = 1 / (1 + np.exp(-x))

print("Input Values:")
print(x)

print("Sigmoid Output:")
print(sigmoid_output)



Activation Function: SIGMOID
Input Values:
[-5  2  0  2  5]
Sigmoid Output:
[0.00669285 0.88079708 0.5        0.88079708 0.99330715]


In [ ]:
print("\nActivation Function: SOFTMAX")

marks = np.array([85, 70, 60])

softmax = np.exp(marks) / np.sum(np.exp(marks))

print("Scores:", marks)
print("Softmax:", softmax)


Activation Function: SOFTMAX
Scores: [85 70 60]
Softmax: [9.99999694e-01 3.05902227e-07 1.38879396e-11]


In [ ]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


model = Sequential([
    Dense(128, activation='relu', input_shape=(10,)),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.summary()

print("Solution: Dropout reduces overfitting.")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,729 (38.00 KB)

 Trainable params: 9,729 (38.00 KB)

 Non-trainable params: 0 (0.00 B)

Solution: Dropout reduces overfitting.


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Larger neural network
model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

print("Solution: More neurons, more layers, and more training.")

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,817 (11.00 KB)

 Trainable params: 2,817 (11.00 KB)

 Non-trainable params: 0 (0.00 B)

Solution: More neurons, more layers, and more training.


In [12]:
# Single Input Perceptron Example


x = 80


w = 0.5


b = 5
theta = 40


weighted_sum = (x * w) + b

print("Input (x):", x)
print("Weight (w):", w)
print("Bias (b):", b)
print("Threshold (θ):", theta)
print("Weighted Sum (Σ):", weighted_sum)


if weighted_sum >= theta:
    output = 1
else:
    output = 0

print("Output:", output)


if output == 1:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")

Input (x): 80
Weight (w): 0.5
Bias (b): 5
Threshold (θ): 40
Weighted Sum (Σ): 45.0
Output: 1
Prediction: PASS


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Training data
X = np.array([
    [80, 90, 5],
    [60, 70, 3],
    [40, 50, 1],
    [90, 95, 6],
    [30, 40, 1],
    [75, 80, 4]
], dtype=float)

# Normalize input
X = X / 100

# Output (1 = PASS, 0 = FAIL)
y = np.array([1, 1, 0, 1, 0, 1])

# Build Multi-Layer Perceptron
model = Sequential([
    Dense(8, activation='relu', input_shape=(3,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(X, y, epochs=100, verbose=1)

# Test data
test = np.array([[85, 90, 5]]) / 100

prediction = model.predict(test)

print("Prediction Value:", prediction[0][0])

if prediction >= 0.5:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")

Epoch 1/100


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6667 - loss: 0.6641
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - accuracy: 0.6667 - loss: 0.6634
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.6667 - loss: 0.6626
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.6667 - loss: 0.6619
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.6667 - loss: 0.6612
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.6667 - loss: 0.6604
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6667 - loss: 0.6597
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6589
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.6582
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6575
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.6567
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.656

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.array([
    [80, 90, 5],
    [60, 70, 3],
    [40, 50, 1],
    [90, 95, 6],
    [30, 40, 1],
    [75, 80, 4]
], dtype=float)

X = X / 100

y = np.array([1, 1, 0, 1, 0, 1])

model = Sequential([
    Dense(8, activation='relu', input_shape=(3,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=100, verbose=0)

loss, accuracy = model.evaluate(X, y, verbose=0)

test = np.array([[85, 90, 5]]) / 100

prediction = model.predict(test, verbose=0)

print("Accuracy:", round(accuracy * 100, 2), "%")
print("Prediction Value:", round(float(prediction[0][0]), 4))

if prediction[0][0] >= 0.5:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")

Accuracy: 66.67 %
Prediction Value: 0.5961
Prediction: PASS
