<a href="https://colab.research.google.com/github/jeevanraajas0210/ITA0604-Machine-Learning/blob/main/products_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

prices = np.random.randint(100, 5001, 20)

print("Product Prices:")
print(prices)

Product Prices:
[4142  688 2282 1279 1240 4312  212 3745  144  997 4902 4322 3808 4783
 3050 3141 1699 4571 3129 3574]


In [4]:
print("First 5 Prices:")
print(prices[:5])

print("Last 5 Prices:")
print(prices[-5:])

First 5 Prices:
[4142  688 2282 1279 1240]
Last 5 Prices:
[3141 1699 4571 3129 3574]


In [5]:
gst_prices = prices * 1.18

print("Prices after 18% GST:")
print(np.round(gst_prices, 2))

Prices after 18% GST:
[4887.56  811.84 2692.76 1509.22 1463.2  5088.16  250.16 4419.1   169.92
 1176.46 5784.36 5099.96 4493.44 5643.94 3599.   3706.38 2004.82 5393.78
 3692.22 4217.32]


In [6]:
above_2500 = gst_prices[gst_prices > 2500]

print("Products costing more than ₹2500:")
print(np.round(above_2500, 2))

Products costing more than ₹2500:
[4887.56 2692.76 5088.16 4419.1  5784.36 5099.96 4493.44 5643.94 3599.
 3706.38 5393.78 3692.22 4217.32]


In [7]:
between_1000_3000 = gst_prices[
    (gst_prices >= 1000) & (gst_prices <= 3000)
]

print("Products between ₹1000 and ₹3000:")
print(np.round(between_1000_3000, 2))

Products between ₹1000 and ₹3000:
[2692.76 1509.22 1463.2  1176.46 2004.82]


In [8]:
print("Minimum Price:", round(np.min(gst_prices), 2))
print("Maximum Price:", round(np.max(gst_prices), 2))

Minimum Price: 169.92
Maximum Price: 5784.36


In [9]:
print("Mean:", round(np.mean(gst_prices), 2))
print("Median:", round(np.median(gst_prices), 2))
print("Variance:", round(np.var(gst_prices), 2))
print("Standard Deviation:", round(np.std(gst_prices), 2))

Mean: 3305.18
Median: 3699.3
Variance: 3367999.22
Standard Deviation: 1835.21


In [10]:
total = np.sum(gst_prices)

print("Total Value of All Products:", round(total, 2))

Total Value of All Products: 66103.6


In [11]:
average = np.mean(gst_prices)

count = np.sum(gst_prices > average)

print("Average Price:", round(average, 2))
print("Number of Products Above Average:", count)

Average Price: 3305.18
Number of Products Above Average: 12


In [12]:
np.savetxt(
    "products.csv",
    gst_prices,
    delimiter=",",
    header="Final_Product_Price",
    comments=""
)

print("File saved successfully as products.csv")

File saved successfully as products.csv
